### ISSUE TITLE
Can't access the exposed ports in Swarm Deployment.

### ISSUE THREAD

**Issue by thabach** [docker/example-voting-app#76]
Heya 

I got issues accessing the voting-app on a swarm deployment through `docker stack`. 

- Does the` frontend` overlay-network not need to be marked as `external` in the `docker-stack.yml` ?
- ... and if so, needs to be created up front ? before the `docker stack deploy` ?

Thx for any help on making this work for me, Christian.

**Comment by gesellix** [comment]
@thabach how did you try to access the voting app?

Please note that the very first deploy takes some time due to the docker pull for every service base image. You can see the current stack state via `docker stack ps example` (with `example` being your custom stack name).

When at least the vote services are running, you should be able to access the voting app at [http://localhost:5000](http://localhost:5000). If that doesn't work, please try your public ip address instead of _localhost_, e.g. [http://192.168.178.42:5000](http://192.168.178.42:5000).

**Comment by ManoMarks** [comment]
@thabach are you still encountering this issue? Does @gesellix's suggestion work?

**Comment by thabach** [comment]
Hey guys, 

thx a lot for the help, I was deploying on Azure on a Docker Swarm cluster provisioned through docker-engine. The problem was that Azure puts a firewall in front of every docker machine and I needed to open the respective port.

Thx again and cheers, Christian.

**Comment by ManoMarks** [comment]
Thanks for the update!

**Comment by pbprathi** [comment]
I am facing the same,Helped me to resolve the same issue. Thanks a lot.

**Comment by zanematthew** [comment]
Did something change in the latest docker? I'm having the same issue.

I followed the steps in this repo, along with the steps here; https://docs.docker.com/get-started/part4/, but when visiting: 192.168.99.100 in my browser I'm getting a "refused to connect." message.

I'm on the latest Docker, VirtualBox, and Mac OS 10.14 (Mojave)
